In [35]:
import pandas as pd
import numpy as np

In [3]:
csv = pd.read_csv('../orders-2022-06-20-00-16-07.csv')

In [21]:
Number = 8421

customer_info = csv.loc[csv['No.'] == Number].iloc[0]
info = f'''
ชื่อลูกค้า : {customer_info['Customer Name']}
สถานะ : {customer_info['Status']}
โทรศัพท์ : {customer_info['Customer Phone']}
อีเมล : {customer_info['Customer Email']}
ที่อยู่ : {customer_info['Customer Address']}
'''
print(info)

ชื่อลูกค้า : Jammie Jamjam
สถานะ : รอการชำระเงิน
โทรศัพท์ : 01132430829, 07478535588 '07597144741
อีเมล : nongfernthai@hotmail.co.uk
ที่อยู่ : 97-99 Vicar Lane LS1 6PJ Leeds

In [54]:
order_list = csv.loc[csv['No.'] == Number][['Item Name', 'Item Qty']]
order_list = order_list.assign(GetItem=4)
order_list

                                   Item Name  Item Qty  GetItem
0   ทุเรียนแกะหมอนทอง (ลังใหญ่) (12000 กรัม)         4        4
1             ทุเรียนหมอนทองลูก (10000 กรัม)         4        4
2       ชิฟฟ่อนหนองพงนก-กล่องใหญ่ (330 กรัม)         5        4
3         ลูกชิ้นเอ็นเนื้อ แชมป์ (1000 กรัม)         5        4
4                    ขนมปังเนยโสด (155 กรัม)        20        4
5                    ขนมปังเนยโสด (155 กรัม)        12        4
6                    ขนมปังเนยโสด (155 กรัม)         3        4
7                    ขนมปังเนยโสด (155 กรัม)         3        4
8                         พริกลาว (100 กรัม)         5        4
9                        เลือดไก่ (350 กรัม)         5        4
10                  พริกขี้หนูสวน (100 กรัม)         5        4
11                   พริกจินดาแดง (100 กรัม)       300        4

In [70]:
def get_report(DF : pd.DataFrame) -> pd.DataFrame:
    data = pd.DataFrame(columns=['Item Name', 'Status', 'Item Qty'])
    for index, row in DF.iterrows():
        n = row['Item Qty'] - row['GetItem']
        if n > 0: # ขาด
            df = pd.DataFrame(
                {
                    'Item Name' : [row['Item Name']],
                    'Status' : ['ขาด'],
                    'Item Qty' : [n]
                }
            )
            # print(f"{row['Item Name']} ขาด")
        elif n < 0: # เกิน
            df = pd.DataFrame(
                {
                    'Item Name' : [row['Item Name']],
                    'Status' : ['เกิน'],
                    'Item Qty' :[-n]
                }
            )
        else:
            continue
        data = pd.concat([data,df], ignore_index=True)
            # print(f"{row['Item Name']} เกิน")
    return data

get_report(order_list)

                              Item Name Status Item Qty
0  ชิฟฟ่อนหนองพงนก-กล่องใหญ่ (330 กรัม)    ขาด        1
1    ลูกชิ้นเอ็นเนื้อ แชมป์ (1000 กรัม)    ขาด        1
2               ขนมปังเนยโสด (155 กรัม)    ขาด       16
3               ขนมปังเนยโสด (155 กรัม)    ขาด        8
4               ขนมปังเนยโสด (155 กรัม)   เกิน        1
5               ขนมปังเนยโสด (155 กรัม)   เกิน        1
6                    พริกลาว (100 กรัม)    ขาด        1
7                   เลือดไก่ (350 กรัม)    ขาด        1
8              พริกขี้หนูสวน (100 กรัม)    ขาด        1
9               พริกจินดาแดง (100 กรัม)    ขาด      296